config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  ignoreempty: false
  keepdot: false
  link_by_default: false
  longkey: true
  showdiff: true
  workdir: ~/.config/dotdrop
dotfiles:
  f_xdefaults:
    dst: ~/.Xdefaults
    src: Xdefaults
profiles:
  warbird:
    dotfiles:
    - f_xdefaults
