actions:
  pre:
    ohmyzsh: test -d ~/.oh-my-zsh || git clone https://github.com/robbyrussell/oh-my-zsh.git
      ~/.oh-my-zsh
    vundle-install: test -d ~/.vim || (mkdir -p ~/.vim/{undodir,bundle} ; git clone
      https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim)
  vundle: vim +VundleClean! +VundleInstall +VundleInstall! +qall
config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  ignoreempty: false
  keepdot: false
  link_by_default: false
  longkey: true
  showdiff: true
  workdir: ~/.config/dotdrop
dotfiles:
  d_config_powerline:
    dst: ~/.config/powerline
    src: config/powerline
  f_bin_lock.sh:
    dst: ~/bin/lock.sh
    src: bin/lock.sh
  f_config_kitty_kitty.conf:
    dst: ~/.config/kitty/kitty.conf
    src: config/kitty/kitty.conf
  f_config_qtile_config.py:
    dst: ~/.config/qtile/config.py
    src: config/qtile/config.py
  f_vim_vimrc:
    actions:
    - vundle-install
    - vundle
    dst: ~/.vim/vimrc
    src: vim/vimrc
  f_xdefaults:
    dst: ~/.Xdefaults
    src: Xdefaults
  f_zshrc:
    actions:
    - ohmyzsh
    dst: ~/.zshrc
    src: zshrc
profiles:
  w0aju:
    dotfiles:
    - d_config_powerline
    - f_config_kitty_kitty.conf
  warbird:
    dotfiles:
    - d_config_powerline
    - f_xdefaults
    - f_vim_vimrc
    - f_zshrc
    - f_config_qtile_config.py
    - f_bin_lock.sh
